In [1]:
# standard python imports
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np
import copy

# pytorch imports
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim.lr_scheduler import StepLR

In [2]:
data = np.load('exp_io_data\CoupledPendula_mean_in7_out7_Tmax1.0_data.npz')
for key, val in data.items():
    print(key)
    exec(key +'=val')

xlist
exp_out_list


In [3]:
x=xlist
y=exp_out_list
print(x.shape)
print(y.shape)

(2000, 14)
(2, 30, 2000, 7, 2)


In [4]:
x_in=x[:,0:7]
x_para=x[:,7:14]
#print(x_in)
#print(x_para)
v_int=np.zeros((2000,7))
x_train=x_in[0:1000,:]
x_train2=x[0:1000,:]
print(x_train.shape)
#print(x)

(1000, 7)


In [5]:

y_temp2=y[0,0:29,:,:,0]
y_temp1=y[0,1:30,:,:,0]
print(y_temp2.shape)
print(y_temp1.shape)
y_v=(y_temp2-y_temp1)#/(1/30)
y_0=np.zeros((1,2000,7))






y_v=np.concatenate((y_0,y_v),axis=0)
print(y_v.shape)

(29, 2000, 7)
(29, 2000, 7)
(30, 2000, 7)


In [6]:
#y1=y[0:1,29:30,:,:,0:1]
print(y.shape)
y_x=y[0,:,:,:,0]
y_new=np.concatenate((y_x,y_v),axis=2)
y_new=torch.from_numpy(y_new)
y_new=torch.transpose(y_new,0,1)
print(y_new.shape)


(2, 30, 2000, 7, 2)
torch.Size([2000, 30, 14])


In [7]:
print(y_new[1,1:2,:])
print(y_new[1,2:3,:])

tensor([[ 8.9990e-01,  3.9747e-01,  6.3987e-01, -1.6053e-01, -2.1341e-01,
         -8.2006e-01,  5.4416e-01,  4.6262e-02,  6.3472e-03,  2.7629e-02,
         -1.1352e-02,  4.7393e-04, -5.0331e-02,  3.8788e-02]],
       dtype=torch.float64)
tensor([[ 7.6473e-01,  3.7754e-01,  5.5941e-01, -1.2792e-01, -2.1344e-01,
         -6.7457e-01,  4.3281e-01,  1.3517e-01,  1.9928e-02,  8.0459e-02,
         -3.2603e-02,  2.7239e-05, -1.4549e-01,  1.1134e-01]],
       dtype=torch.float64)


In [8]:
F=3 #Fth frame

y_train=y_new[0:1000,F:F+1,:]
print(y_train.shape)

torch.Size([1000, 1, 14])


In [9]:



class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()

        self.layer1 = nn.Linear(14, 14 ,bias=True)
        self.layer2 = nn.Linear(14, 14,bias=True)
        self.layer3 = nn.Linear(14, 14,bias=True)
        #self.layer4 = nn.Linear(14, 14,bias=True)
        #self.layer5 = nn.Linear(14, 14,bias=True)
        self.layer4 = nn.Linear(14, 14,bias=True)
    def forward(self, x,activation="RELU"):
        # Max pooling over a (2, 2) window
        
        x = torch.flatten(x, 1) # flatten all dimensions except the batch dimension
        x = x+torch.sigmoid(self.layer1(x))
        x = x+torch.sigmoid(self.layer2(x))
        x = x+torch.sigmoid(self.layer3(x))
        #x = x+torch.sigmoid(self.layer4(x))
        #x = x+torch.sigmoid(self.layer5(x))
        x = self.layer4(x)
        #x = F.relu(self.layer4(x))
        #x = F.relu(self.layer5(x))
        #x = torch.sigmoid(self.layer6(x))
        return x.float()


net = Net()
print(net)

Net(
  (layer1): Linear(in_features=14, out_features=14, bias=True)
  (layer2): Linear(in_features=14, out_features=14, bias=True)
  (layer3): Linear(in_features=14, out_features=14, bias=True)
  (layer4): Linear(in_features=14, out_features=14, bias=True)
)


In [ ]:



class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()

        self.layer1 = nn.Linear(14, 14 ,bias=True)
        self.layer2 = nn.Linear(14, 14,bias=True)
        self.layer3 = nn.Linear(14, 14,bias=True)
        #self.layer4 = nn.Linear(14, 14,bias=True)
        #self.layer5 = nn.Linear(14, 14,bias=True)
        self.layer4 = nn.Linear(14, 7,bias=True)
    def forward(self, x,activation="RELU"):
        
        if activation=="RELU":
            x = torch.flatten(x, 1) # flatten all dimensions except the batch dimension
            x = x+0.1*(self.layer1(x))
            x = x+0.1*(self.layer2(x))
            x = x+0.1*(self.layer3(x))
            #x = x+torch.sigmoid(self.layer4(x))
            #x = x+torch.sigmoid(self.layer5(x))
            x = self.layer4(x)
            #x = F.relu(self.layer4(x))
            #x = F.relu(self.layer5(x))
            #x = torch.sigmoid(self.layer6(x))
        if activation=="SIG":
            x = torch.flatten(x, 1) # flatten all dimensions except the batch dimension
            x = x+torch.sigmoid(self.layer1(x))
            x = x+torch.sigmoid(self.layer2(x))
            x = x+torch.sigmoid(self.layer3(x))
            #x = x+torch.sigmoid(self.layer4(x))
            #x = x+torch.sigmoid(self.layer5(x))
            x = self.layer4(x)
            #x = F.relu(self.layer4(x))
            #x = F.relu(self.layer5(x))
            #x = torch.sigmoid(self.layer6(x))            
        return x.float()


net = Net()
print(net)




In [10]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

8
torch.Size([14, 14])


In [11]:
x_data=torch.tensor(x_train2)
input = x_data
out = net(input,"SIG")
print(out)
print(out.shape)

tensor([[-2.9795, -1.4794, -1.1413,  ..., -1.4645, -0.9520, -2.6713],
        [-2.8495, -1.8427, -1.0279,  ..., -1.5492, -0.7971, -2.3189],
        [-2.8449, -1.7865, -0.9964,  ..., -1.3630, -0.4737, -2.4789],
        ...,
        [-2.8814, -1.5936, -0.7804,  ..., -1.1017, -0.6299, -2.2588],
        [-2.8584, -2.0040, -0.7086,  ..., -1.1401, -0.9443, -2.4606],
        [-2.7919, -1.9122, -0.9796,  ..., -1.3159, -0.6416, -2.4778]],
       grad_fn=<AddmmBackward>)
torch.Size([1000, 14])


In [12]:
net.zero_grad()
out.backward(torch.randn(1000,14))

In [13]:
target=y_train
target_new=target.view(1000,14).float()
print(target_new.shape)
criterion=nn.MSELoss()
loss=criterion(out,target_new)
print(loss)

torch.Size([1000, 14])
tensor(2.3995, grad_fn=<MseLossBackward>)


In [14]:
for i in range(60/num_layers):
    loss
    sum_loss+=loss
    sum_loss.backward()

NameError: name 'num_layers' is not defined

In [16]:
import torch.optim as optim
optimizer = torch.optim.Adam(params, lr=0.01, betas=(0.9, 0.999), eps=1e-09, weight_decay=0.1, amsgrad=False)  #adam optimizer
    
for i in range(200):
    optimizer.zero_grad()   # zero the gradient buffers
    output = net(input)
    loss = criterion(output, target_new).float()
    loss.backward()
    optimizer.step()
    print(loss)


tensor(0.2184, grad_fn=<MseLossBackward>)
tensor(0.2315, grad_fn=<MseLossBackward>)
tensor(0.2324, grad_fn=<MseLossBackward>)
tensor(0.2256, grad_fn=<MseLossBackward>)
tensor(0.2256, grad_fn=<MseLossBackward>)
tensor(0.2260, grad_fn=<MseLossBackward>)
tensor(0.2206, grad_fn=<MseLossBackward>)
tensor(0.2191, grad_fn=<MseLossBackward>)
tensor(0.2227, grad_fn=<MseLossBackward>)
tensor(0.2229, grad_fn=<MseLossBackward>)
tensor(0.2189, grad_fn=<MseLossBackward>)
tensor(0.2172, grad_fn=<MseLossBackward>)
tensor(0.2193, grad_fn=<MseLossBackward>)
tensor(0.2205, grad_fn=<MseLossBackward>)
tensor(0.2191, grad_fn=<MseLossBackward>)
tensor(0.2177, grad_fn=<MseLossBackward>)
tensor(0.2179, grad_fn=<MseLossBackward>)
tensor(0.2185, grad_fn=<MseLossBackward>)
tensor(0.2183, grad_fn=<MseLossBackward>)
tensor(0.2180, grad_fn=<MseLossBackward>)
tensor(0.2178, grad_fn=<MseLossBackward>)
tensor(0.2176, grad_fn=<MseLossBackward>)
tensor(0.2174, grad_fn=<MseLossBackward>)
tensor(0.2175, grad_fn=<MseLossBac

In [ ]:
print(y_new.shape)
y_test=y_new[1000:2000,F:F+1,:]
print(y_test.shape)

In [ ]:
x_test=torch.tensor(x_test)
test_out=net(x_test)
print(test_out.shape)
#LOSS = criterion(test_out, y_test)
# print(test_out)
# print(y_test)
y_test_new=y_test.squeeze(1)
print(y_test_new.shape)
# test_loss=criterion(y_test_new,test_out)
# print(test_loss)

In [ ]:
plt.plot(y_test_new.flatten(), 5*test_out.detach().numpy().flatten(), '.')
plt.title('Training')
plt.xlabel('y')
plt.ylabel('y_pred')

In [ ]:
def plot_dt_exp_comparison(yexp, ypred):

    fig, axs = plt.subplots(nrows = 3, ncols = 3, figsize = [10,8], dpi = 100, sharex=True, sharey=True)
    for i in range(9):
        plt.sca(axs.flatten()[i])
        plt.plot(ypred[i], '.-', lw = 1, c = 'k', alpha = 0.5, label = 'digital twin prediction')
        plt.plot(yexp[i], '.-', lw = 1, c = 'b', alpha = 0.5, label = 'experimental outcome')
        plt.xlabel('# pendulum')
        plt.ylabel('output angle')
        plt.title(f'Initial conditions {i}')
        plt.grid()
    plt.legend()
    plt.tight_layout()
    plt.savefig('img/coupled_pendula_dt_examples.png')
    plt.show()
    
plot_dt_exp_comparison(y_test_new,10*test_out.detach())

In [ ]:

class Net2(nn.Module):

    def __init__(self):
        super(Net2, self).__init__()

        self.layer1 = nn.Linear(14, 120)
        self.layer2 = nn.Linear(120, 120)
        self.layer3 = nn.Linear(120, 120)
        self.layer4 = nn.Linear(120, 84)
        self.layer5 = nn.Linear(84, 42)
        self.layer6 = nn.Linear(42, 7)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        
        x = torch.flatten(x, 1) # flatten all dimensions except the batch dimension
        x = F.relu(self.layer1(x))
        x = x+F.relu(self.layer2(x))
        x = x+F.relu(self.layer3(x))
        x = F.relu(self.layer4(x))
        x = F.tanh(self.layer5(x))
        x = F.relu(self.layer6(x))
        return x


net2 = Net2()
print(net2)

params2 = list(net2.parameters())
print(len(params2))
print(params2[0].size())

In [ ]:
x_data=torch.tensor(x)
input = x_data
out = net2(input)
print(out)
print(out.shape)

In [ ]:
target=y1[0:1000,:,:]
target_new=target.view(1000,7)

In [ ]:
import torch.optim as optim
optimizer = torch.optim.Adam(params, lr=0.001, betas=(0.9, 0.999), eps=1e-06, weight_decay=0.1, amsgrad=False)  #adam optimizer
    
for i in range(200):
    optimizer.zero_grad()   # zero the gradient buffers
    output = net2(input)
    loss = criterion(output, target_new)
    loss.backward()
    optimizer.step()
    print(loss)
